INSERT into relation (parent_id,name,color) values
(0, 'Warrior', 'red'),
(0, 'Wizard', 'green'),
(0, 'Priest', 'white'),
(0, 'Rogue', 'yellow'),
(1, 'Fighter', 'blue'),
(1, 'Paladin', 'lighblue'),
(1, 'Ranger', 'lighgreen'),
(2, 'Mage', 'grey'),
(2, 'Specialist wizard', 'lightgrey'),
(3, 'Cleric', 'red'),
(3, 'Druid', 'green'),
(3, 'Priest of specific mythos', 'white'),
(4, 'Thief', 'yellow'),
(4, 'Bard', 'blue'),
(13, 'Assassin', 'lighblue');
